[project]
name = "sp-lr1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-math>=0.0.1",
    "sympy>=1.14.0",
]
